### ISSUE TITLE
Support oclHashcat v2.01 or later versions

### ISSUE THREAD

**Issue by halexan** [Rich5/pyHashcat#10]
Please update pyHashcat, so that it can support oclHashcat v2.01 or later versions. Thanks a lot

**Comment by Rich5** [comment]
Have you tried it yet on v2.01? Since pyHashcat is simply passing command line parameters most of the typical arguments _should_ work with the latest version. Unless you are using new features that were specifically introduced in the newer versions then pyHashcat would have to be updated. Unfortunately, I can't support development on this at the moment. I'll leave the issue open because it does need updates, but I can't promise it will be soon. 

If you would like to update yourself it's fairly straight forward. Any new hash types would need to be added to **hash_type_dict**. Similarly, any new  command line switches would need to be added to **cmd_short_switch** or **cmd_equal_required**.  Pull requests are always welcome :) Sorry I can't be of more help right now.

**Comment by halexan** [comment]
I setup pyhashcat and run it by myself. But there is an error. 

`[*] Variables reset to defaults
[*] Checking architecture: 64 bit
[*] Checking OS type: Windows
[*] Using OCL version
[*] Using cmd: oclHashcat64.exe
[*] Building argv
[*] (0) Rules files specified. Verifying files...
[*] Starting Straight (0) attack
--------- Hashcat CMD Test ---------
C:\Work\Crack\Software\oclHashcat-2.01\oclHashcat64.exe -m 0 -a 0 MD5_Test.txt example.dict
------------------------------------
[*] Program exited with code: -99
[*] Program exited with code: -99`

I'm not very good at python, I'm doing my best to find the reason.

**Comment by Rich5** [comment]
can you post your code where you called pyHashcat please?

**Comment by Rich5** [comment]
Also, exit code 1 means "exhausted"  so from the output you posted it appears to have worked. Are you sure you're example.dict has the plaintext equivalents to the hashes in your MD5_Test.hash file?

**Comment by halexan** [comment]
The code is:
`import pyHashcat

hashcat = pyHashcat.oclHashcatWrapper("D:\software\oclHashcat-2.10b131", gcard_type='ocl', verbose=True)
hashcat.hash_file = "MD5_Test.hash"
hashcat.words_files.append("example.dict")
hashcat.hash_type = "MD5"
hashcat.straight()

while hashcat.is_running():
	print hashcat.stdout()

hashcat.stop()`

The result is:

> [\*] Variables reset to defaults
[\*] Checking architecture: 64 bit
[\*] Checking OS type: Windows
[\*] Using OCL version
[\*] Using cmd: oclHashcat64 
[\*] Building argv
[\*] \(0\) Rules files specified. Verifying files...
[\*] Starting Straight \(0\) attack
[\+] STDIN: D:\software\oclHashcat-2.10b131\oclHashcat64  -m 0 -a 0 MD5_Test.hash example.dict
[\*] STDOUT thread started
[\*] STDERR thread started
.
.       lots of empty lines
.
oclHashcat v2.01 (ge688e94) starting...
.
.      lots of empty lines
.
[\*] Program exited with code: -1

**Comment by Rich5** [comment]
Ok, so the exit codes mean the following:

```
-1 = error
0 = cracked
1 = exhausted 
2 = aborted
```

The error comes from the hashcat process itself. Can you run the oclhashcat command line with no problem? Try running _D:\software\oclHashcat-2.10b131\oclHashcat64 -m 0 -a 0 MD5_Test.hash example.dict_ on the command line? What happens? If it doesn't just jump right into cracking then that could be the start of the problem. 

As for all the empty lines that comes from this line:

`while hashcat.is_running(): print hashcat.stdout()`

which is just a very simple stream gobbler. The fact that it's empty probably means that the hashcat process didn't start correctly.

**Comment by halexan** [comment]
I tried running:
"D:\software\oclHashcat-2.10b131\oclHashcat64 -m 0 -a 0 D:\software\oclHashcat-2.10b131\MD5_Test.hash D:\software\oclHashcat-2.10b131\example.dict"
oclHashcat works good, no errors.

So I changed my code to:

> import pyHashcat
hashcat = pyHashcat.oclHashcatWrapper("D:\software\oclHashcat-2.10b133", gcard_type='ocl', verbose=True)
hashcat.hash_file = "D:\software\oclHashcat-2.10b133\MD5_Test.hash"
hashcat.words_files.append("D:\software\oclHashcat-2.10b133\example.dict")
hashcat.hash_type = "MD5"
hashcat.straight()
while hashcat.is_running():   print hashcat.stdout()
hashcat.stop()

The result is:

> [\*] Variables reset to defaults
[\*] Checking architecture: 64 bit
[\*] Checking OS type: Windows
[\*] Using OCL version
[\*] Using cmd: oclHashcat64 
[\*] Building argv
[\*] \(0\) Rules files specified. Verifying files...
[\*] Starting Straight \(0\) attack
[\+] STDIN: D:\Study\Crack\GPU\software\oclHashcat-2.10b133\oclHashcat64  -m 0 -a 0 D:\Study\Crack\GPU\software\oclHashcat-2.10b133\MD5_Test.hash D:\Study\Crack\GPU\software\oclHashcat-2.10b133\example.dict
[\*] STDOUT thread started
[\*] STDERR thread started
.
.
.   lots of empty lines
.
.
[\*] Program exited with code: 0

"0 = cracked" means that oclHashcat cracked the hash. Maybe something wrong with `hashcat.stdout()`. The output of `hashcat.stdout()` is lots of empty lines. Are those empty lines come from `out = self.q.get_nowait()` in `hashcat.stdout()`?

**Comment by Rich5** [comment]
If the cracked hash is showing up in the pot file then it appears to be working probably. The hashcat.stout() is a very raw way to get some output from hashcat stout. The way hashcat displays output doesn't allow for a good way to retrieve information. If you're expecting to see the interactive display like you see when you run hashcat normally that is unlikely to be the case.

**Comment by Rich5** [comment]
To answer your questions about the emtpy lines. yes, that is from the code you described. It's expected behavior. I suppose adding the --status switch might help

**Comment by halexan** [comment]
Cracked hash is showing up in the pot file. It seems that oclHashcat works probably. Only the output of `hashcat.stdout()` is not correct. As you said, the way hashcat displays output doesn't allow for a good way to retrieve information. Maybe python is not suitable to get the output of hashcat?

I notice that you wrote oclhashcatAPITest.c. Is the "API" suitable to retrieve information? In oclhastcat issue #9. jsteube said:

> For example you could start list what else do you need. Invokation is one thing but I guess you also want a function to get stats and so on. **For that I'd suggest making a new function that does nothing else than to return the values one could need, for example to read the speed, get the number of cracked hashes, and so on...**

Make some new functions to get the values from hashcat, is this way correct to retrieve information?

**Comment by Rich5** [comment]
It's not that the stout is not correct it's that the hashcat process is not sending anything to stdout because it's designed for user input to view the status. Regardless I understand your problem. Again, the --status switch may help some. What specific information are you trying to retrieve? 

oclhashcat API is not ready to be used and is still in development. There is no function to retrieve information just yet. If you read more of the conversation between atom and I you can see the after some thorough testing has been done atom will create a function to return a structure with information about the running process. Then the code has to be pulled into the master. If you're looking for a more prepackaged solution you may have to look elsewhere until the API is done. At this point atom appears to be focused on other features to improve performance, and I can only focus on this in my spare time. If you would like to help out pull requests are welcome here and I'm sure at the hashcat master branch. Hope this helps some.

**Comment by halexan** [comment]
Thanks for your help! I will continue focus on the API of hashcat (oclhashcat issue #9). I think this issue can be closed.
